Repository victorflx7/Sabidos-API-Core, pull requests merged in 2025-09, with the labels that each got.

#23 Estrutura inicial da Api (Arquitetura de Pastas e Solução do Projeto) #1
  .gitignore
  SabidosAPI-Core/.dockerignore
  SabidosAPI-Core/.gitignore
  SabidosAPI-Core/Controllers/UserController.cs
  SabidosAPI-Core/DTOs/UserResponseDto.cs
  SabidosAPI-Core/Data/AppDbContext.cs
  SabidosAPI-Core/Dockerfile
  SabidosAPI-Core/Mappings/UserProfile.cs
  SabidosAPI-Core/Models/User.cs
  SabidosAPI-Core/Program.cs
  SabidosAPI-Core/Properties/launchSettings.json
  SabidosAPI-Core/SabidosAPI-Core.csproj
  SabidosAPI-Core/SabidosAPI-Core.http
  SabidosAPI-Core/SabidosAPI-Core.sln
  SabidosAPI-Core/Services/UserService.cs
  SabidosAPI-Core/appsettings.Development.json
  SabidosAPI-Core/appsettings.json
Labels: start / structure

#42 Costruindo a Classe resumos
  SabidosAPI-Core/Models/Resumo.cs
Labels: enhancement

#52 Criar Classe Evento no Models #44
  SabidosAPI-Core/Models/Evento.cs
Labels: enhancement

#59 Criação do Serviço (Evento) de Leitura (GetAll e GetById) #6
  SabidosAPI-Core/Data/AppDbContext.cs
  SabidosAPI-Core/Models/Evento.cs
  SabidosAPI-Core/Services/EventoService.cs
Labels: enhancement

#61 Criando Resumo service getall e getbyid
  SabidosAPI-Core/Services/ResumoService.cs
Labels: enhancement

#62 Implementação do serviço (resumo) atualização
  SabidosAPI-Core/Services/ResumoService.cs
Labels: enhancement

#101 Config/100 criação da fábrica de testes customwebapplicationfactory
  Api.Tests/Api.Tests.csproj
  Api.Tests/Api.Tests.sln
  Api.Tests/Integration/CustomWebApplicationFactory.cs
  Api.Tests/UnitTest1.cs
Labels: start / structure, Test

#106 DTO para criação e atualização de flashcards (FlashcardCreateUpdateDto)
  SabidosAPI-Core/DTOs/FlashcardCreateUpdateDto.cs
Labels: enhancement

#111 Configuração de Cors no Program.cs #97
  SabidosAPI-Core/Program.cs
Labels: start / structure, Test
